# Generated by Django 2.0.7 on 2018-07-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date_created'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='date_updated'),
        ),
    ]
